version: '3.1'
services:
  db:
    image: mysql
    container_name: graphql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - graphql_data:/var/lib/mysql

volumes:
  graphql_data: