server:
  error:
    include-stacktrace: on_trace_param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/compras?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      format_sql: false
      ddl-auto: update
    show-sql: true

logging:
#  pattern:
#    console: {%d{yyy-MM-dd HH:mm:ss} %~5level %logger{36} ~ %msg%n}
  level:
    org:
      hibernate:
        SQL: debug
