server:
  error:
    include-stacktrace: on_trace_param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/compras?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      format_sql: false
      ddl-auto: update
      show-sql: true
      formart_sql: true
    # Cache
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

logging:
#  pattern:
#    console: {%d{yyy-MM-dd HH:mm:ss} %~5level %logger{36} ~ %msg%n}
  level:
    org:
      hibernate:
        SQL: debug
        cache: debug